### ISSUE TITLE
Missing ) after argument list

### ISSUE THREAD

**Issue by florianginetta** [brainly/html-sketchapp-example#1]
When trying to run `npm run inject http://www.sketchapp.com` I get an error in `inject.js:12`

```
/Users/florians/Documents/html-sketchapp-example-master 2/src/inject.js:12
puppeteer.launch().then(async browser => {
                        ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

```

Looks like somethings’s not up-to-date on my machine. Any idea?

**Comment by florianginetta** [comment]
I think I answered it myself. I updated NodeJS to make it work ;) Thanks!
