### ISSUE TITLE
UnhandledPromiseRejectionWarning error

### ISSUE THREAD

**Issue by andrewcio** [brainly/html-sketchapp-example#4]
Cloned the example repo and followed the instructions as written, was hit with an `UnhandledPromiseRejectionWarning` error shown below:

```
(node:3009) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './build/page2layers.bundle.js'
  -- ASYNC --
    at Frame.<anonymous> (/Users/<user>/repos/html-sketchapp-example/node_modules/puppeteer/lib/helper.js:144:27)
    at Page.addScriptTag (/Users/<user>/repos/html-sketchapp-example/node_modules/puppeteer/lib/Page.js:395:29)
    at Page.<anonymous> (/Users/<user>/repos/html-sketchapp-example/node_modules/puppeteer/lib/helper.js:145:23)
    at puppeteer.launch.then (/Users/<user>/repos/html-sketchapp-example/src/inject.js:20:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
- Below the above error, the terminal just hangs.
- I am running `node v11.11.0` and `npm 6.9.0` on Mojave 10.14.3. 
- Same result when using `node v10.15.3` and `npm 6.4.1` (managed via nvm). 
- I made sure to update the dependencies as well. Using `html-sketchapp v4.2.0` as reported in my `package.json` file.

I also received a similar error on High Sierra before updating my OS this past weekend. Thought I had something up with my install (computer needed a cleaning) so I did a fresh install as I upgraded. 

Is there a specific version of node that is required?

**Comment by andrewcio** [comment]
Well, after digging in a second time, I simply changed the output filename in `webpack.config.js` to `'../build/page2layers.bundle.js'` (one directory up). 

After that, everything works real well.

**Comment by andrewcio** [comment]
Digging in again, clearly user error. I was messing with the webpack when troubleshooting unrelated errors. Closing this because this is what happens when a designer gets cheeky. 🙈
